[supervisord]
nodaemon=true

[program:ngw_geofencer]
command=python /app/geofencer/ngw_geofencer.py
directory=/app/geofencer
autorestart=true

[program:flask]
command=python /app/geofencer/app.py
directory=/app/geofencer
autorestart=true
