[supervisord]
nodaemon=true

[program:ngw_geofencer]
command=python /app/ngw_geofencer.py
autorestart=true

[program:geometry_modifier]
command=python /app/geometry_modifier.py
autorestart=true

[program:flask]
command=python /app/app.py
autorestart=true
